# Generated by Django 3.2.13 on 2022-07-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_activated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
