# Generated by Django 3.2.13 on 2022-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Asset name')),
                ('ticker', models.CharField(max_length=6, verbose_name='Ticker')),
                ('price', models.FloatField(verbose_name='Price')),
                ('marketcap', models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Market cap')),
            ],
        ),
    ]
