# Generated by Django 3.2.13 on 2022-07-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_userasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userasset',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Total amount'),
        ),
        migrations.AddField(
            model_name='userasset',
            name='average_buy_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Average buy'),
        ),
        migrations.AddField(
            model_name='userasset',
            name='average_sell_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Average sell'),
        ),
        migrations.AddField(
            model_name='userasset',
            name='max_amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Max amount'),
        ),
    ]
