# Generated by Django 3.2.13 on 2022-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20220729_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='max_amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Max amount'),
        ),
    ]
