# Generated by Django 3.2.13 on 2022-07-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_userasset_max_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userasset',
            name='max_amount',
            field=models.FloatField(blank=True, verbose_name='Max amount'),
        ),
    ]
