# Generated by Django 3.2.13 on 2022-07-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_userasset_max_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userasset',
            name='max_amount',
        ),
    ]
