# Generated by Django 3.2.13 on 2022-07-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_alter_userasset_max_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='marketcap',
        ),
        migrations.AddField(
            model_name='asset',
            name='ath',
            field=models.FloatField(blank=True, null=True, verbose_name='All time high'),
        ),
        migrations.AddField(
            model_name='asset',
            name='circulating_supply',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Circulating supply'),
        ),
        migrations.AddField(
            model_name='asset',
            name='high_24h',
            field=models.FloatField(blank=True, null=True, verbose_name='High 24 h'),
        ),
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.URLField(null=True, unique=False,blank=True,default='https://'),
        ),
        migrations.AddField(
            model_name='asset',
            name='low_24h',
            field=models.FloatField(blank=True, null=True, verbose_name='Low 24 h'),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Market Cap'),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap_rank',
            field=models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Market cap rank'),
        ),
        migrations.AddField(
            model_name='asset',
            name='max_supply',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Max supply'),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_24h',
            field=models.FloatField(blank=True, null=True, verbose_name='Price change 24h'),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_percentage_24h',
            field=models.FloatField(blank=True, null=True, verbose_name='Price change percentage 24h'),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_supply',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Total supply'),
        ),
        migrations.AddField(
            model_name='asset',
            name='total_volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Total volume'),
        ),
    ]
