# Generated by Django 3.2.13 on 2022-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20220730_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.URLField(null=True, unique=False,blank=True,default='https://'),
        ),
    ]
