# Generated by Django 3.2.13 on 2022-07-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_alter_asset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='market_cap_rank',
            field=models.PositiveSmallIntegerField(db_index=True, null=True, verbose_name='Market cap rank'),
        ),
    ]
