# Generated by Django 3.2.13 on 2022-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_auto_20220730_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='name_id',
            field=models.CharField(db_index=True, default='coin', max_length=128, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
