# Generated by Django 3.2.13 on 2022-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20220730_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name_id',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='id'),
        ),
    ]
