# Generated by Django 3.2.13 on 2022-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
