# Generated by Django 3.2.13 on 2022-07-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20220729_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, default='29-07-22', null=True, verbose_name='Transaction date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='buy', max_length=5, verbose_name='Transaction type'),
        ),
    ]
