# Generated by Django 3.2.13 on 2022-07-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, default='07/29/22', null=True, verbose_name='Transaction date'),
        ),
    ]
