# Generated by Django 3.2.13 on 2022-07-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_alter_userasset_max_amount'),
        ('transaction', '0009_alter_transaction_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.userasset'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, default='07/30/22', null=True, verbose_name='Transaction date'),
        ),
    ]
