# Generated by Django 3.2.13 on 2022-07-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20220730_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
